# Copyright Broadcom, Inc. All Rights Reserved.
# SPDX-License-Identifier: APACHE-2.0

services:
  postgresql-master:
    image: docker.io/bitnami/postgresql:17
    ports:
      - '5433:5432'
    volumes:
      - 'postgresql_master_data:/bitnami/postgresql'
    environment:
      - POSTGRESQL_USERNAME=dbuser
      - POSTGRESQL_PASSWORD=dbpassword
      - POSTGRESQL_DATABASE=shopper-database
    networks:
      - bigdata_dev

networks:
  bigdata_dev:
    driver: bridge

volumes:
  postgresql_master_data:
    driver: local